POST http://localhost:8080/events/1/register 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzM3NDU3Mzc2LCJ1c2VySWQiOjJ9.0oxO2nYJxvOjMe0X3ojhWCQMVL4aIlBTHO63wSkt8Fg